<script lang="ts">
  /*
   * Every icon design.pen uses, keyed by the name IT uses.
   *
   * Generated by scripts/design/icons.ts — run it again when the design
   * changes rather than editing this by hand. Keying on the design's own
   * names is what lets a screen be read beside its artboard without
   * translating: the artboard says `icon=git-branch` and so does the markup.
   */
  import Activity from '@lucide/svelte/icons/activity';
  import Apple from '@lucide/svelte/icons/apple';
  import ArrowRight from '@lucide/svelte/icons/arrow-right';
  import Bell from '@lucide/svelte/icons/bell';
  import BookOpen from '@lucide/svelte/icons/book-open';
  import Bot from '@lucide/svelte/icons/bot';
  import Check from '@lucide/svelte/icons/check';
  import ChevronDown from '@lucide/svelte/icons/chevron-down';
  import ChevronRight from '@lucide/svelte/icons/chevron-right';
  import CircleCheck from '@lucide/svelte/icons/circle-check';
  import CircleX from '@lucide/svelte/icons/circle-x';
  import Code from '@lucide/svelte/icons/code';
  import Coins from '@lucide/svelte/icons/coins';
  import Container from '@lucide/svelte/icons/container';
  import Copy from '@lucide/svelte/icons/copy';
  import Download from '@lucide/svelte/icons/download';
  import Ellipsis from '@lucide/svelte/icons/ellipsis';
  import EllipsisVertical from '@lucide/svelte/icons/ellipsis-vertical';
  import ExternalLink from '@lucide/svelte/icons/external-link';
  import Factory from '@lucide/svelte/icons/factory';
  import FileText from '@lucide/svelte/icons/file-text';
  import FolderGit2 from '@lucide/svelte/icons/folder-git-2';
  import GitBranch from '@lucide/svelte/icons/git-branch';
  import GitCommitHorizontal from '@lucide/svelte/icons/git-commit-horizontal';
  import GitMerge from '@lucide/svelte/icons/git-merge';
  import GitPullRequest from '@lucide/svelte/icons/git-pull-request';
  import Globe from '@lucide/svelte/icons/globe';
  import GripVertical from '@lucide/svelte/icons/grip-vertical';
  import Hand from '@lucide/svelte/icons/hand';
  import History from '@lucide/svelte/icons/history';
  import Images from '@lucide/svelte/icons/images';
  import Kanban from '@lucide/svelte/icons/kanban';
  import KeyRound from '@lucide/svelte/icons/key-round';
  import LayoutDashboard from '@lucide/svelte/icons/layout-dashboard';
  import Lightbulb from '@lucide/svelte/icons/lightbulb';
  import Link from '@lucide/svelte/icons/link';
  import List from '@lucide/svelte/icons/list';
  import ListChecks from '@lucide/svelte/icons/list-checks';
  import Loader from '@lucide/svelte/icons/loader';
  import Map from '@lucide/svelte/icons/map';
  import MessageSquare from '@lucide/svelte/icons/message-square';
  import Palette from '@lucide/svelte/icons/palette';
  import Pause from '@lucide/svelte/icons/pause';
  import PenTool from '@lucide/svelte/icons/pen-tool';
  import Pencil from '@lucide/svelte/icons/pencil';
  import Play from '@lucide/svelte/icons/play';
  import Plug from '@lucide/svelte/icons/plug';
  import Plus from '@lucide/svelte/icons/plus';
  import Rocket from '@lucide/svelte/icons/rocket';
  import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
  import Save from '@lucide/svelte/icons/save';
  import Search from '@lucide/svelte/icons/search';
  import Server from '@lucide/svelte/icons/server';
  import Settings from '@lucide/svelte/icons/settings';
  import Settings2 from '@lucide/svelte/icons/settings-2';
  import ShieldCheck from '@lucide/svelte/icons/shield-check';
  import Sparkles from '@lucide/svelte/icons/sparkles';
  import SquareCheck from '@lucide/svelte/icons/square-check';
  import Terminal from '@lucide/svelte/icons/terminal';
  import Ticket from '@lucide/svelte/icons/ticket';
  import Timer from '@lucide/svelte/icons/timer';
  import Trash2 from '@lucide/svelte/icons/trash-2';
  import TriangleAlert from '@lucide/svelte/icons/triangle-alert';
  import Undo2 from '@lucide/svelte/icons/undo-2';
  import User from '@lucide/svelte/icons/user';
  import Workflow from '@lucide/svelte/icons/workflow';
  import X from '@lucide/svelte/icons/x';
  import Zap from '@lucide/svelte/icons/zap';

  type IconProps = { size?: number; class?: string; 'aria-hidden'?: 'true' };

  let {
    name,
    size = 16,
    class: klass = '',
  }: { name: string; size?: number; class?: string } = $props();

  import type { Component } from 'svelte';

  const LUCIDE: Record<string, Component<IconProps>> = {
    'activity': Activity,
    'apple': Apple,
    'arrow-right': ArrowRight,
    'bell': Bell,
    'book-open': BookOpen,
    'bot': Bot,
    'check': Check,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'circle-check': CircleCheck,
    'circle-x': CircleX,
    'code': Code,
    'coins': Coins,
    'container': Container,
    'copy': Copy,
    'download': Download,
    'ellipsis': Ellipsis,
    'ellipsis-vertical': EllipsisVertical,
    'external-link': ExternalLink,
    'factory': Factory,
    'file-text': FileText,
    'folder-git-2': FolderGit2,
    'git-branch': GitBranch,
    'git-commit-horizontal': GitCommitHorizontal,
    'git-merge': GitMerge,
    'git-pull-request': GitPullRequest,
    'globe': Globe,
    'grip-vertical': GripVertical,
    'hand': Hand,
    'history': History,
    'images': Images,
    'kanban': Kanban,
    'key-round': KeyRound,
    'layout-dashboard': LayoutDashboard,
    'lightbulb': Lightbulb,
    'link': Link,
    'list': List,
    'list-checks': ListChecks,
    'loader': Loader,
    'map': Map,
    'message-square': MessageSquare,
    'palette': Palette,
    'pause': Pause,
    'pen-tool': PenTool,
    'pencil': Pencil,
    'play': Play,
    'plug': Plug,
    'plus': Plus,
    'rocket': Rocket,
    'rotate-ccw': RotateCcw,
    'save': Save,
    'search': Search,
    'server': Server,
    'settings': Settings,
    'settings-2': Settings2,
    'shield-check': ShieldCheck,
    'sparkles': Sparkles,
    'square-check': SquareCheck,
    'terminal': Terminal,
    'ticket': Ticket,
    'timer': Timer,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    'undo-2': Undo2,
    'user': User,
    'workflow': Workflow,
    'x': X,
    'zap': Zap,
  };

  // Lucide dropped the brand marks over trademark; the design still needs
  // them, because they are how somebody picks a provider.
  const BRANDS: Record<string, string> = {
    'gitlab': `<path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.06 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z"/>`,
    'github': `<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/>`,
  };

  const Rendered = $derived(LUCIDE[name]);
</script>

{#if BRANDS[name]}
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
    class={klass}
    aria-hidden="true"
  >
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    {@html BRANDS[name]}
  </svg>
{:else if Rendered}
  <Rendered {size} class={klass} aria-hidden="true" />
{/if}
