#!/usr/bin/env bun
/**
 * Generates `apps/web/src/components/Icon.svelte` from the icon names
 * `design.pen` actually uses.
 *
 * Keyed by the DESIGN's names, so a screen's markup reads exactly as its
 * artboard does — `<Icon name="git-branch" />` against `icon [Icon]
 * icon=git-branch` — and a reader can hold the two side by side without
 * translating. Generated rather than hand-written so the set cannot drift
 * from the file; re-run it after the design changes.
 *
 *   bun scripts/design/icons.ts
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { artboards, icons, load } from './resolve';

const ROOT = resolve(import.meta.dir, '../..');
const used = new Set<string>();
for (const board of artboards(load())) for (const icon of icons(board)) used.add(icon);
const names = [...used].sort();

// Lucide dropped the brand marks over trademark, so these two are drawn here.
// The design needs them: they are how somebody picks a provider.
const BRANDS: Record<string, string> = {
  gitlab:
    '<path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.06 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z"/>',
  github:
    '<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/>',
};

const missing = names.filter(
  (n) =>
    !(n in BRANDS) &&
    !existsSync(`${ROOT}/apps/web/node_modules/@lucide/svelte/dist/icons/${n}.js`),
);
if (missing.length > 0) {
  console.error(`no icon for: ${missing.join(', ')}`);
  process.exit(1);
}

const identifier = (name: string) =>
  name
    .split('-')
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join('');

const lucide = names.filter((n) => !(n in BRANDS));
const lines = [
  '<script lang="ts">',
  '  /*',
  '   * Every icon design.pen uses, keyed by the name IT uses.',
  '   *',
  '   * Generated by scripts/design/icons.ts — run it again when the design',
  "   * changes rather than editing this by hand. Keying on the design's own",
  '   * names is what lets a screen be read beside its artboard without',
  '   * translating: the artboard says `icon=git-branch` and so does the markup.',
  '   */',
  ...lucide.map((n) => `  import ${identifier(n)} from '@lucide/svelte/icons/${n}';`),
  '',
  "  type IconProps = { size?: number; class?: string; 'aria-hidden'?: 'true' };",
  '',
  '  let {',
  '    name,',
  '    size = 16,',
  "    class: klass = '',",
  '  }: { name: string; size?: number; class?: string } = $props();',
  '',
  "  import type { Component } from 'svelte';",
  '',
  '  const LUCIDE: Record<string, Component<IconProps>> = {',
  ...lucide.map((n) => `    '${n}': ${identifier(n)},`),
  '  };',
  '',
  '  // Lucide dropped the brand marks over trademark; the design still needs',
  '  // them, because they are how somebody picks a provider.',
  '  const BRANDS: Record<string, string> = {',
  ...Object.entries(BRANDS).map(([n, d]) => `    '${n}': \`${d}\`,`),
  '  };',
  '',
  '  const Rendered = $derived(LUCIDE[name]);',
  '</script>',
  '',
  '{#if BRANDS[name]}',
  '  <svg',
  '    width={size}',
  '    height={size}',
  '    viewBox="0 0 24 24"',
  '    fill="none"',
  '    stroke="currentColor"',
  '    stroke-width="2"',
  '    stroke-linecap="round"',
  '    stroke-linejoin="round"',
  '    class={klass}',
  '    aria-hidden="true"',
  '  >',
  '    <!-- eslint-disable-next-line svelte/no-at-html-tags -->',
  '    {@html BRANDS[name]}',
  '  </svg>',
  '{:else if Rendered}',
  '  <Rendered {size} class={klass} aria-hidden="true" />',
  '{/if}',
  '',
];

writeFileSync(`${ROOT}/apps/web/src/components/Icon.svelte`, lines.join('\n'));
console.log(
  `${names.length} icons (${lucide.length} from Lucide, ${Object.keys(BRANDS).length} drawn here)`,
);
