/**
 * What each screen takes from `design.pen`, named.
 *
 * A screen built from an artboard and then left alone drifts: somebody
 * rewords a button, somebody else redraws the artboard, and nothing says so.
 * This is the list that binds the two together. `takes` are phrases that
 * must be in BOTH the artboard and the screen's source; `omits` are phrases
 * that must be in the artboard and NOT in the source, each with the reason
 * it was left out.
 *
 * The phrases are the fixed copy — headings, labels, button text, the
 * sentences that explain a thing. Never the artboard's sample data: "Add
 * OAuth login with Google" is a ticket somebody invented for a picture, and
 * a screen that contained it would be wrong, not right.
 *
 * An omission that stops being true is as much a failure as a label that
 * drifts: if the artboard loses "Self-hosted Git", the note explaining why
 * we do not offer it is stale, and the check says so.
 */

export interface Screen {
  artboard: string;
  files: string[];
  takes: string[];
  omits?: { label: string; why: string }[];
}

const APP = 'apps/web/src/routes/(app)';
const UI = 'apps/web/src/components';
/** Where the words live: every screen takes its copy from the Mongolian catalogue. */
const MN = 'apps/web/src/lib/i18n/mn.ts';

export const SCREENS: Screen[] = [
  {
    artboard: '00 Login',
    files: ['apps/web/src/routes/login/+page.svelte', MN],
    takes: [
      'Code Factory',
      'Даалгавраас нэгтгэх хүсэлт хүртэл — автоматаар',
      'Агентууд тодорхойлолт бичиж, интерфейсийг pen.dev дээр зурж, төлөвлөөд хэрэгжүүлж, нэгтгэх хүсэлт нээнэ.',
      'Даалгавар',
      'Тодорхойлолт',
      'Дизайн · pen.dev',
      'Төлөвлөгөө',
      'Хөгжүүлэлт',
      'Нэвтрэх',
      'Ажлын бүртгэлээрээ үргэлжлүүлнэ үү.',
      '-аар үргэлжлүүлэх',
      'GitLab',
      'GitHub',
      'эсвэл имэйлээр',
      'Ажлын имэйл',
      'Нууц үг',
      'Нэвтэрснээр юу ч холбогдохгүй. Репозиториео дараагийн алхамд нэмнэ.',
      'Netgroup · Claude CLI ба pen.dev дээр ажилладаг',
    ],
    omits: [
      {
        label: '92%',
        why: 'A figure on the sign-in page is either invented or the workspace record shown to someone not yet signed in; the hero says what the product does instead.',
      },
      {
        label: 'pen.dev дизайн батлагдсан',
        why: 'The second floating widget names a real ticket (#142) and its review; before sign-in that is either made up or somebody else work, so it is not drawn.',
      },
    ],
  },
  {
    // The frame every signed-in screen opens with: the floating top bar.
    artboard: '01 Dashboard',
    files: [`${UI}/TopNav.svelte`, `${APP}/+layout.svelte`, MN],
    takes: [
      'Code Factory',
      'Хяналт',
      'Даалгавар',
      'Репозитори',
      'Дамжлага',
      'Агент',
      'Ур чадвар',
      'Хайх',
      'Шинэ даалгавар',
    ],
    omits: [
      {
        label: '⌘K',
        why: 'The search field hints at a key binding the product does not have; a shortcut hint that does nothing is a promise the screen cannot keep.',
      },
    ],
  },
  {
    artboard: '01 Dashboard',
    files: [
      `${APP}/+page.svelte`,
      `${UI}/DashboardTickets.svelte`,
      `${UI}/ApprovalPanel.svelte`,
      `${UI}/FirstAttemptRing.svelte`,
      `${UI}/WeekChart.svelte`,
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'Даалгавар бүр өөрийн дамжлагаар явна — зурвас бүр тэр дамжлагын нэг алхам',
      'Бүгдийг харах →',
      'Ажиллаж буй',
      'Анхаарал хэрэгтэй',
      'Дараалалд',
      'Дууссан',
      'алхам',
      'Таны батлалт хүлээж байна',
      'шалтгааныг харах',
      '-р байр',
      'нээгдлээ · хүн шийднэ',
      'Таны батлалт хэрэгтэй',
      'Агент ажлаа дуусгаад таныг хүлээж байна',
      'бэлэн болсон',
      'Батлах',
      'Эхний оролдлогоор амжилттай',
      'сүүлийн 30 хоног',
      'Нэгтгэх хүсэлт',
      'энэ 7 хоногт нээсэн',
      'Хөгжүүлж байна',
      'pen.dev дээр зурж байна',
      'Тодорхойлж байна',
      'Даалгавар гаргаж байна',
      'Стандарт',
      'Хяналттай',
      'Хурдан засвар',
      'Лх',
      'Пү',
      'Ба',
      'Бя',
      'Ня',
      'Да',
      'Мя',
    ],
    omits: [
      {
        label: 'Өнөөдрийн зардал',
        why: 'The week tile shows the tokens the steps finished today processed ("Өнөөдрийн токен"), not their cost in dollars: tokens are what the engines report, and what people compare runs by.',
      },
      {
        label: '4 дэлгэц · 38 мин өмнө',
        why: 'The approvals tile reads the board, which knows how long a gate has waited but not how many screens its design step exported; every waiting item says when it became ready instead.',
      },
    ],
  },
  {
    artboard: '02 Repositories',
    files: [`${APP}/repositories/+page.svelte`, `${UI}/ConnectRepository.svelte`, MN],
    takes: [
      'Холбогдсон репозитори',
      'Даалгавар бүр нэг репозиторид харьяалагдана. Даалгавар үүсгэхийн тулд эхлээд репозиториео холбоно уу.',
      'Репозитори холбох',
      ' GitLab · ',
      ' GitHub',
      'Идэвхтэй даалгавар',
      ' репозитори дээр',
      'Анхаарал хэрэгтэй',
      'Холбогдсон',
      'Токен дууссан',
      ' дамжлага',
      'СҮҮЛИЙН АЖИЛ',
      'идэвхтэй даалгавар',
      ' дууссан',
      'Токен хугацаа дууссан — шинэ даалгавар эхлэхгүй',
      'Токен солих',
    ],
  },
  {
    artboard: '03 Connect Repository',
    files: [`${UI}/ConnectRepository.svelte`, MN],
    takes: [
      'Репозитори холбох',
      'эрх шаардлагатай.',
      'Үйлчилгээгээ сонгоно уу',
      'GitLab',
      'GitHub',
      'Сонгосон',
      'Репозиторийн хаяг',
      'Хандалтын токен',
      'Шаардлагатай эрх: ',
      'Шифрлэгдэж хадгалагдана',
      'Шинэ даалгаврын үндсэн дамжлага',
      'Болих',
      'Шалгаад холбох',
    ],
    omits: [
      {
        label: 'Өөрийн Git сервер',
        why: 'This version connects GitLab.com and GitHub.com and nothing else (FR-014a). A third option that refused every address would be worse than no option.',
      },
    ],
  },
  {
    artboard: '04 Tickets Board',
    files: [
      `${APP}/tickets/+page.svelte`,
      `${UI}/TicketCard.svelte`,
      `${UI}/StepBar.svelte`,
      'apps/web/src/lib/state-words.ts',
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'даалгавар · төлөв бүрээр. Даалгавар бүр өөрийн дамжлагаар явна.',
      'Шинэ даалгавар',
      'Бүх репозитори',
      'Бүх дамжлага',
      'Бүх хүн үүсгэсэн',
      'Хүлээлгэнд',
      'Ажиллаж буй',
      'Батлахыг хүлээж буй',
      'Дууссан',
      'Амжилтгүй',
      'Дараалалд · ',
      '-р байр',
      'Эхлүүлэхэд бэлэн',
      ' батлуулах',
      'нээгдлээ',
      'Тодорхойлолт',
      'Хөгжүүлэлт',
      'Стандарт',
      'Хурдан засвар',
      'Хяналттай',
    ],
    omits: [
      {
        label: 'MR !86 нэгтгэгдсэн',
        why: 'Merging belongs to the provider and a person, never to the factory (nothing is merged automatically), and the application is not told when it happens; a done card says the merge request was opened.',
      },
      {
        label: 'Дизайн батлуулах · 4 дэлгэц',
        why: 'The board reads which step a checkpoint gates, not how many screens that step exported; the card names the step to approve.',
      },
    ],
  },
  {
    artboard: '05 Create Ticket',
    files: [`${APP}/tickets/new/+page.svelte`, `${UI}/FilePicker.svelte`, MN],
    takes: [
      'Даалгаврууд',
      'Шинэ даалгавар',
      'Юу хийлгэхээ бичнэ үү',
      'Репозитори',
      'Заавал',
      'Гарчиг',
      'Google-ийн хажууд Apple нэвтрэлт нэмэх',
      'Тайлбар',
      'Энгийн үгээр бичсэн ч болно. Тодорхойлолт агент тодруулах асуултаа өөрөө асууна.',
      'Хүлээн авах шалгуур',
      'Мөр бүрд нэг. Хөгжүүлэлт агент бүгдийг нь биелүүлнэ.',
      'Бүх хэрэглэгчид /login дээр Apple товч харагдана',
      'Дамжлага',
      'Зөвхөн энэ даалгаврын алхмуудыг өөрчилнө',
      ' алхам',
      'Стандарт',
      'Хяналттай',
      'Хурдан засвар',
      'Ноороглох',
      'Үүсгээд эхлүүлэх',
      'Юу болох вэ',
      ' дамжлага · ',
      'Тодорхойлолт агент',
      'Дизайн агент',
      'Төлөвлөгөө агент',
      'Даалгавар агент',
      'Хөгжүүлэлт агент',
      'Интерфейс өөрчлөгдөх бол',
      'pen.dev · ',
      'Нэгтгэх хүсэлт нээх',
      'Салбар түлхэгдэж, хүсэлт нээгдэж, даалгавар хаагдана',
      'Энэ даалгавар интерфейс өөрчилж байгаа эсэхийг Тодорхойлолт агент шийднэ. Хэрэв тийм бол Дизайн агент pen.dev дээр зурж, код бичихээс өмнө та дэлгэцүүдийг хянана.',
    ],
    omits: [
      {
        label: 'Ойролцоо зардал ≈ ',
        why: 'The estimate under the form is in tokens ("Ойролцоогоор ≈ … токен"), taken from comparable finished runs; a dollar figure would be a second unit for a number the run pages show in tokens.',
      },
      {
        label: 'Шалгуур нэмэх',
        why: 'The criteria are one per line in a text field, which the form has always submitted; a row-per-criterion editor with its own add button would be new behaviour (FR-025).',
      },
      {
        label: 'Тодорхойлолт → Дизайн → Төлөвлөгөө → Даалгавар → Хөгжүүлэлт → MR',
        why: 'A pipeline card shows its bar and description; the chosen pipeline\'s steps are listed in full, by name, beside the form under "Юу болох вэ", so a second list in the card would repeat it.',
      },
    ],
  },
  {
    artboard: '06 Ticket Run',
    files: [
      `${APP}/tickets/[id]/+page.svelte`,
      `${UI}/TicketHead.svelte`,
      `${UI}/StepTracker.svelte`,
      `${UI}/LiveLog.svelte`,
      `${UI}/ArtifactViewer.svelte`,
      `${UI}/RunDetails.svelte`,
      `${UI}/LaunchPanel.svelte`,
      MN,
    ],
    takes: [
      'Ажиллаж буй',
      ' эхэлсэн',
      ' алхам',
      'хугацаа',
      'Түр зогсоох',
      'Цуцлах',
      'Тодорхойлолт',
      'Дизайн · pen.dev',
      'Төлөвлөгөө',
      'Даалгавар',
      'Хөгжүүлэлт',
      ' · ажиллаж буй',
      'Нэгтгэх хүсэлт',
      'хүлээгдэж',
      'Гаралт',
      'Артефакт',
      'Ажиллуулах',
      'Мэдээлэл',
      'ШУУД',
    ],
    omits: [
      {
        label: 'зарцуулсан · төсөв ',
        why: 'The head shows the tokens the run has used so far ("токен ашигласан") and no budget beside it: the dollar ceiling is a limit each step is stopped at, not an allowance the run is spending down.',
      },
    ],
  },
  {
    artboard: '07 Approval Checkpoint',
    files: [`${APP}/tickets/[id]/approve/+page.svelte`, `${UI}/TicketHead.svelte`, MN],
    takes: [
      'Даалгаврууд',
      'Таны батлалт хүлээж буй',
      ' үүсгэсэн',
      ' эхэлсэн',
      'одоогоор ',
      'Ажиллагаа цуцлах',
      'Хяналтын цэг: ',
      'код бичихээс өмнө',
      ' ажлаа дуусгалаа. Та батлах, өөрчлөлт хүсэх, эсвэл өөрөө засах хүртэл дамжлага түр зогсоно.',
      'Өөрчлөлт хүсэх',
      'Батлаад үргэлжлүүлэх',
      ' засах',
      'Таны тэмдэглэл ',
      ' засагдаад дахин энд зогсоно.',
      ' руу буцаах',
      'Явц',
      'дууссан',
      'Батлалт хүлээж буй',
      ' (та)',
    ],
    omits: [
      {
        label: 'Батлалт: Ana тодорхойлолтыг баталлаа',
        why: 'The timeline names a decision by what was decided; who decided it is recorded on the approval but the timeline has never carried it, and adding it is new behaviour, not presentation.',
      },
    ],
  },
  {
    // The pipelines list (`pipelines/+page.svelte`) has no artboard of its
    // own: it is drawn from the kit's tiles, chips and buttons, and has no
    // entry here because there is no artboard to hold it to.
    artboard: '08 Pipeline Builder',
    files: [
      `${APP}/pipelines/[id]/+page.svelte`,
      `${UI}/PipelineBuilder.svelte`,
      `${UI}/StepNode.svelte`,
      'apps/web/src/lib/services/pipeline.ts',
      MN,
    ],
    takes: [
      'Дамжлага',
      ' репозитори ашиглаж байна',
      'Алхмуудаа хүссэн дарааллаар чирнэ үү. Дамжлага үргэлжлэхээс өмнө хүн харах ёстой газарт хяналтын цэг нэмээрэй.',
      'Хуулбарлах',
      'Туршилтаар ажиллуулах',
      'Эхлэл: даалгавар үүсэх',
      'Нэгтгэх хүсэлт нээх → даалгавар хаах',
      'Нөхцөлт',
      'Алхам нэмэх',
      'Зураг дээр чирэх эсвэл холбоос дээрх + дарна уу.',
      'Хүний хяналтын цэг',
      'Хэн нэгэн батлах хүртэл зогсоно',
      'Дизайн алхам',
      'pen.dev CLI-аар дэлгэц зурна',
      'Агент алхам',
      'Claude CLI-аар агентаа ажиллуулна',
      'Shell команд',
      'Тусгаарлагдсан орчинд скрипт ажиллуулна (lint, build)',
      'Мэдэгдэх',
      'Slack / и-мэйл / webhook',
      'Таны агентууд',
      'Захиалгат',
      'pen.dev',
      ' бичнэ',
      ' ц хүлээнэ, дараа нь ',
    ],
    omits: [
      {
        label: 'Хяналтын цэг: тодорхойлолт батлах',
        why: 'A checkpoint stores who approves it and how long it waits, not what it is for; the card says "Хүний хяналтын цэг" and its rules, and naming what it gates would be a new field, not presentation.',
      },
      {
        label: 'Зөвхөн интерфейстэй үед',
        why: 'A conditional step states its condition in the same words the ticket form uses for it ("Интерфейс өөрчлөгдөх бол"), so the two screens never describe one condition two ways.',
      },
      {
        label: 'Багийн аль ч гишүүн · 24 ц хүлээнэ, дараа нь автоматаар үргэлжилнэ',
        why: 'The approvers are the workspace, not a team, and the card says so in the words the step editor uses; the timeout half is taken as it is drawn.',
      },
    ],
  },
  {
    artboard: '09 Agents',
    files: [`${APP}/agents/+page.svelte`, `${UI}/AgentCard.svelte`, MN],
    takes: [
      'Агент',
      'Агент бүр өөрийн заавар, загвар, хэрэгсэл, ур чадвартайгаар ажиллана. Дизайн агент pen.dev CLI дээр, бусад нь Claude CLI дээр ажиллана.',
      'Шинэ агент',
      'Үндсэн',
      'Нөхцөлт',
      'Захиалгат',
      'Загвар',
      'Хэрэгсэл',
      'Ур чадвар',
      'Хөдөлгүүр',
      'Гаралт',
      'pen.dev CLI',
      'ui.pen + PNG screens',
      ' дамжлагад · ',
      ' ажиллагаа',
      'Хараахан ашиглаагүй',
      'Засах',
      'Дамжлагадаа өөрийн алхам нэмэх',
    ],
  },
  {
    artboard: '10 Agent Editor',
    files: [`${APP}/agents/[id]/+page.svelte`, MN],
    takes: [
      'Үндсэн',
      ' · засварласан',
      'Өөрчлөлт зөвхөн шинэ ажиллагаанд үйлчилнэ. Ажиллаж буй даалгаврууд эхэлсэн хувилбараа хадгална.',
      'Анхны төлөвт буцаах',
      'Системийн заавар',
      'CLI ажиллахын өмнө ',
      ' болгон оруулна. Даалгаврын өгөгдлийг {{variables}}-аар бичнэ.',
      '.claude/agents/',
      'Загвар ба хязгаар',
      'Загвар',
      'Дээд зардал',
      'Дээд хугацаа',
      'Дээд эргэлт',
      'Зөвшөөрөгдсөн хэрэгсэл',
      'CLI-д --allowedTools болгон дамжина',
      'Унших',
      'Репозиторийн аль ч файлыг унших',
      'Bash',
      'Shell команд ажиллуулах (тест, build)',
      'Git түлхэлт',
      'Дуусахад салбарыг түлхэх',
      'WebFetch',
      'Гадаад хаягаас татах',
      'Хавсаргасан ур чадвар',
      'Удирдах →',
      'Нэмэх',
    ],
    omits: [
      {
        label: 'Sandbox-д турших',
        why: 'Nothing behind it exists — a run needs an orchestrator and a container host — and a button that does nothing is worse than no button.',
      },
      {
        label: 'Засах / Бичих',
        why: 'Editing an existing file and creating one are separate permissions (FR-039), so each has its own toggle rather than one shared switch.',
      },
    ],
  },
  {
    artboard: '11 Skills',
    files: [`${APP}/skills/+page.svelte`, MN],
    takes: [
      'Ур чадвар',
      'Аль ч агент ашиглаж болох дахин хэрэглэгдэх зааврын файлууд. Ажиллагаа бүрт .claude/skills/ дотор хуулагдана.',
      'Шинэ ур чадвар',
      'Ур чадвар хайх',
      ' агент',
      ' агент ашиглаж байна',
      '/SKILL.md',
      'Түүх',
      'Устгах',
      'Ур чадвар хадгалах',
      'Нэр',
      'Тайлбар (агент хэзээ ашиглахаа мэдэхийн тулд харна)',
      'Агуулга (Markdown)',
      'Урьдчилан харах',
    ],
  },
  {
    artboard: '12 Settings',
    files: [`${APP}/settings/+page.svelte`, MN],
    takes: [
      'Тохиргоо',
      'Ажлын талбарын тохиргоо. Зөвхөн администратор өөрчилнө.',
      'Бүх холболтыг шалгах',
      'Ажлын талбар',
      'Ажиллуулагч',
      'Sandbox (Docker)',
      'Claude CLI ба түлхүүр',
      'Дизайн (pen.dev)',
      'Зардлын хязгаар',
      'Гишүүд',
      'Мэдэгдэл',
      'Даалгаврын ажиллагаа бүрийг ажиллуулагч гүйцэтгэж, дарааллыг өөрөө удирдана. Апп зөвхөн өгөгдөл хадгалж, явцыг харуулна.',
      'Холбогдсон',
      'Ажиллуулагчийн хаяг',
      'Нэвтрэх токен',
      'Ажиллагаа эхлүүлэх, хүлээлтийг үргэлжлүүлэхэд ашиглана',
      'Буцах дуудлага (ажиллуулагч → апп)',
      '/api/hooks/orchestrator',
      'Холболт шалгах',
      'Sandbox · Docker',
      'Ажиллагаа бүр репозитори, Claude CLI, хэрэгслүүдээ агуулсан шинэ орчин авна.',
      'Ажиллуулагчийн образ',
      'Нэг орчны CPU',
      'Санах ой',
      'Дээд хугацаа',
      'Хөгжүүлэлтийн үед сүлжээнд нэвтрэх',
      'Дизайн · pen.dev',
      'Зөвхөн дизайн алхамд ашиглана. Дэлгэцүүд зураг болон гарч, .pen файл кодтойгоо хамт commit хийгдэнэ.',
      'Нэвтэрсэн',
      'Бүртгэлийн түлхүүр',
    ],
    omits: [
      {
        label: 'Docker хост',
        why: "Which container host the runner uses is the runner's own configuration; the application has no field for it, and one here would describe a setting nothing reads.",
      },
      {
        label: 'Хэвийн',
        why: "The sandbox is reached through the runner and has no check of its own; a status on its tile would repeat the runner's under another name.",
      },
      {
        label: 'Зэрэг ажиллах орчин',
        why: 'How many runs execute at once is the workspace limit in the cost-limits tile (maxConcurrentRuns), stated there once rather than twice.',
      },
      {
        label: 'Хүсэлт нээгдсэний дараа орчныг устгах',
        why: "The workspace keeps a failed run's sandbox for a number of hours rather than switching removal on or off; the field says how many, which the toggle could not.",
      },
      {
        label: 'npm install-д шаардлагатай. Бүрэн офлайн ажиллагаанд унтраана.',
        why: 'The network option explains what actually refuses a run when it is off — agent and design steps need the network to reach the model — which the shorter note leaves out.',
      },
      {
        label: 'Үндсэн дизайн загвар',
        why: "A design step's model belongs to the step, set in the pipeline builder; the tile says so instead of offering a workspace default nothing reads.",
      },
      {
        label: 'Экспорт',
        why: 'Export settings belong to the design step too, for the same reason.',
      },
    ],
  },
  {
    artboard: '14 Design Review',
    files: [
      `${APP}/tickets/[id]/design/+page.svelte`,
      `${UI}/TicketHead.svelte`,
      `${UI}/ScreenGallery.svelte`,
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'Дизайн батлахыг хүлээж буй',
      'Ажиллагаа цуцлах',
      'Хяналтын цэг: код бичихээс өмнө дэлгэцүүдийг хянана уу',
      'Дизайн агент pen.dev CLI-аар ',
      ' дэлгэц зурсан.',
      'Одоогоор юу ч хэрэгжүүлээгүй.',
      'Батлавал ',
      ' рүү шилжинэ.',
      'Өөрчлөлт хүсэх',
      'Батлаад үргэлжлүүлэх',
      'Дэлгэцүүд',
      ' экспортлосон',
      // The committed source, where it lives: opened, or fetched (FR-064e).
      'pen.dev дээр нээх',
      '.pen татах',
      'Яагаад энэ даалгаврыг зурсан бэ',
      'Тодорхойлолт агент шийдсэн · ',
      'Дэлгэцүүдийг эдгээртэй тулгана уу',
      'Батласны дараа',
    ],
    omits: [
      {
        label: 'Дизайн алхам · 2м 41с · $0.42',
        why: "The head carries what every ticket head carries — branch, author, start, spend — and the design step's own time and cost are under the column beside the screens, where the step is described.",
      },
    ],
  },
];
