/**
 * What each screen takes from `design.pen`, named.
 *
 * A screen built from an artboard and then left alone drifts: somebody
 * rewords a button, somebody else redraws the artboard, and nothing says so.
 * This is the list that binds the two together. `takes` are phrases that
 * must be in BOTH the artboard and the screen's source; `omits` are phrases
 * that must be in the artboard and NOT in the source, each with the reason
 * it was left out.
 *
 * The phrases are the fixed copy — headings, labels, button text, the
 * sentences that explain a thing. Never the artboard's sample data: "Add
 * OAuth login with Google" is a ticket somebody invented for a picture, and
 * a screen that contained it would be wrong, not right.
 *
 * An omission that stops being true is as much a failure as a label that
 * drifts: if the artboard loses "Self-hosted Git", the note explaining why
 * we do not offer it is stale, and the check says so.
 */

export interface Screen {
  artboard: string;
  files: string[];
  takes: string[];
  omits?: { label: string; why: string }[];
}

const APP = 'apps/web/src/routes/(app)';
const UI = 'apps/web/src/components';
/** Where the words live: every screen takes its copy from the Mongolian catalogue. */
const MN = 'apps/web/src/lib/i18n/mn.ts';

export const SCREENS: Screen[] = [
  {
    artboard: '00 Login',
    files: ['apps/web/src/routes/login/+page.svelte', MN],
    takes: [
      'Code Factory',
      'Даалгавраас нэгтгэх хүсэлт хүртэл — автоматаар',
      'Агентууд тодорхойлолт бичиж, интерфейсийг pen.dev дээр зурж, төлөвлөөд хэрэгжүүлж, нэгтгэх хүсэлт нээнэ.',
      'Даалгавар',
      'Тодорхойлолт',
      'Дизайн · pen.dev',
      'Төлөвлөгөө',
      'Хөгжүүлэлт',
      'Нэвтрэх',
      'Ажлын бүртгэлээрээ үргэлжлүүлнэ үү.',
      '-аар үргэлжлүүлэх',
      'GitLab',
      'GitHub',
      'эсвэл имэйлээр',
      'Ажлын имэйл',
      'Нууц үг',
      'Нэвтэрснээр юу ч холбогдохгүй. Репозиториео дараагийн алхамд нэмнэ.',
      'Netgroup · Claude CLI ба pen.dev дээр ажилладаг',
    ],
    omits: [
      {
        label: '92%',
        why: 'A figure on the sign-in page is either invented or the workspace record shown to someone not yet signed in; the hero says what the product does instead.',
      },
      {
        label: 'pen.dev дизайн батлагдсан',
        why: 'The second floating widget names a real ticket (#142) and its review; before sign-in that is either made up or somebody else work, so it is not drawn.',
      },
    ],
  },
  {
    // The frame every signed-in screen opens with: the floating top bar.
    artboard: '01 Dashboard',
    files: [`${UI}/TopNav.svelte`, `${APP}/+layout.svelte`, MN],
    takes: [
      'Code Factory',
      'Хяналт',
      'Даалгавар',
      'Репозитори',
      'Дамжлага',
      'Агент',
      'Ур чадвар',
      'Хайх',
      'Шинэ даалгавар',
    ],
    omits: [
      {
        label: '⌘K',
        why: 'The search field hints at a key binding the product does not have; a shortcut hint that does nothing is a promise the screen cannot keep.',
      },
    ],
  },
  {
    artboard: '01 Dashboard',
    files: [
      `${APP}/+page.svelte`,
      `${UI}/DashboardTickets.svelte`,
      `${UI}/ApprovalPanel.svelte`,
      `${UI}/FirstAttemptRing.svelte`,
      `${UI}/WeekChart.svelte`,
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'Даалгавар бүр өөрийн дамжлагаар явна — зурвас бүр тэр дамжлагын нэг алхам',
      'Бүгдийг харах →',
      'Ажиллаж буй',
      'Анхаарал хэрэгтэй',
      'Дараалалд',
      'Дууссан',
      'алхам',
      'Таны батлалт хүлээж байна',
      'шалтгааныг харах',
      '-р байр',
      'нээгдлээ · хүн шийднэ',
      'Таны батлалт хэрэгтэй',
      'Агент ажлаа дуусгаад таныг хүлээж байна',
      'бэлэн болсон',
      'Батлах',
      'Эхний оролдлогоор амжилттай',
      'сүүлийн 30 хоног',
      'Нэгтгэх хүсэлт',
      'энэ 7 хоногт нээсэн',
      'Өнөөдрийн зардал',
      'Хөгжүүлж байна',
      'pen.dev дээр зурж байна',
      'Тодорхойлж байна',
      'Даалгавар гаргаж байна',
      'Стандарт',
      'Хяналттай',
      'Хурдан засвар',
      'Лх',
      'Пү',
      'Ба',
      'Бя',
      'Ня',
      'Да',
      'Мя',
    ],
    omits: [
      {
        label: '4 дэлгэц · 38 мин өмнө',
        why: 'The approvals tile reads the board, which knows how long a gate has waited but not how many screens its design step exported; every waiting item says when it became ready instead.',
      },
    ],
  },
  {
    artboard: '02 Repositories',
    files: [`${APP}/repositories/+page.svelte`, `${UI}/ConnectRepository.svelte`, MN],
    takes: [
      'Холбогдсон репозитори',
      'Даалгавар бүр нэг репозиторид харьяалагдана. Даалгавар үүсгэхийн тулд эхлээд репозиториео холбоно уу.',
      'Репозитори холбох',
      ' GitLab · ',
      ' GitHub',
      'Идэвхтэй даалгавар',
      ' репозитори дээр',
      'Анхаарал хэрэгтэй',
      'Холбогдсон',
      'Токен дууссан',
      ' дамжлага',
      'СҮҮЛИЙН АЖИЛ',
      'идэвхтэй даалгавар',
      ' дууссан',
      'Токен хугацаа дууссан — шинэ даалгавар эхлэхгүй',
      'Токен солих',
    ],
  },
  {
    artboard: '03 Connect Repository',
    files: [`${UI}/ConnectRepository.svelte`, MN],
    takes: [
      'Репозитори холбох',
      'эрх шаардлагатай.',
      'Үйлчилгээгээ сонгоно уу',
      'GitLab',
      'GitHub',
      'Сонгосон',
      'Репозиторийн хаяг',
      'Хандалтын токен',
      'Шаардлагатай эрх: ',
      'Шифрлэгдэж хадгалагдана',
      'Шинэ даалгаврын үндсэн дамжлага',
      'Болих',
      'Шалгаад холбох',
    ],
    omits: [
      {
        label: 'Өөрийн Git сервер',
        why: 'This version connects GitLab.com and GitHub.com and nothing else (FR-014a). A third option that refused every address would be worse than no option.',
      },
    ],
  },
  {
    artboard: '04 Tickets Board',
    files: [
      `${APP}/tickets/+page.svelte`,
      `${UI}/TicketCard.svelte`,
      `${UI}/StepBar.svelte`,
      'apps/web/src/lib/state-words.ts',
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'даалгавар · төлөв бүрээр. Даалгавар бүр өөрийн дамжлагаар явна.',
      'Шинэ даалгавар',
      'Бүх репозитори',
      'Бүх дамжлага',
      'Бүх хүн үүсгэсэн',
      'Хүлээлгэнд',
      'Ажиллаж буй',
      'Батлахыг хүлээж буй',
      'Дууссан',
      'Амжилтгүй',
      'Дараалалд · ',
      '-р байр',
      'Эхлүүлэхэд бэлэн',
      ' батлуулах',
      'нээгдлээ',
      'Тодорхойлолт',
      'Хөгжүүлэлт',
      'Стандарт',
      'Хурдан засвар',
      'Хяналттай',
    ],
    omits: [
      {
        label: 'MR !86 нэгтгэгдсэн',
        why: 'Merging belongs to the provider and a person, never to the factory (nothing is merged automatically), and the application is not told when it happens; a done card says the merge request was opened.',
      },
      {
        label: 'Дизайн батлуулах · 4 дэлгэц',
        why: 'The board reads which step a checkpoint gates, not how many screens that step exported; the card names the step to approve.',
      },
    ],
  },
  {
    artboard: '05 Create Ticket',
    files: [`${APP}/tickets/new/+page.svelte`, `${UI}/FilePicker.svelte`, MN],
    takes: [
      'Даалгаврууд',
      'Шинэ даалгавар',
      'Юу хийлгэхээ бичнэ үү',
      'Репозитори',
      'Заавал',
      'Гарчиг',
      'Google-ийн хажууд Apple нэвтрэлт нэмэх',
      'Тайлбар',
      'Энгийн үгээр бичсэн ч болно. Тодорхойлолт агент тодруулах асуултаа өөрөө асууна.',
      'Хүлээн авах шалгуур',
      'Мөр бүрд нэг. Хөгжүүлэлт агент бүгдийг нь биелүүлнэ.',
      'Бүх хэрэглэгчид /login дээр Apple товч харагдана',
      'Дамжлага',
      'Зөвхөн энэ даалгаврын алхмуудыг өөрчилнө',
      ' алхам',
      'Стандарт',
      'Хяналттай',
      'Хурдан засвар',
      'Ойролцоо зардал ≈ ',
      'Ноороглох',
      'Үүсгээд эхлүүлэх',
      'Юу болох вэ',
      ' дамжлага · ',
      'Тодорхойлолт агент',
      'Дизайн агент',
      'Төлөвлөгөө агент',
      'Даалгавар агент',
      'Хөгжүүлэлт агент',
      'Интерфейс өөрчлөгдөх бол',
      'pen.dev · ',
      'Нэгтгэх хүсэлт нээх',
      'Салбар түлхэгдэж, хүсэлт нээгдэж, даалгавар хаагдана',
      'Энэ даалгавар интерфейс өөрчилж байгаа эсэхийг Тодорхойлолт агент шийднэ. Хэрэв тийм бол Дизайн агент pen.dev дээр зурж, код бичихээс өмнө та дэлгэцүүдийг хянана.',
    ],
    omits: [
      {
        label: 'Шалгуур нэмэх',
        why: 'The criteria are one per line in a text field, which the form has always submitted; a row-per-criterion editor with its own add button would be new behaviour (FR-025).',
      },
      {
        label: 'Тодорхойлолт → Дизайн → Төлөвлөгөө → Даалгавар → Хөгжүүлэлт → MR',
        why: 'A pipeline card shows its bar and description; the chosen pipeline\'s steps are listed in full, by name, beside the form under "Юу болох вэ", so a second list in the card would repeat it.',
      },
    ],
  },
  {
    artboard: '06 Ticket Run',
    files: [
      `${APP}/tickets/[id]/+page.svelte`,
      `${UI}/TicketHead.svelte`,
      `${UI}/StepTracker.svelte`,
      `${UI}/LiveLog.svelte`,
      `${UI}/RunResults.svelte`,
      `${UI}/ArtifactViewer.svelte`,
      `${UI}/RunDetails.svelte`,
      `${UI}/LaunchPanel.svelte`,
      MN,
    ],
    takes: [
      'Ажиллаж буй',
      ' эхэлсэн',
      ' алхам',
      'хугацаа',
      'зарцуулсан · төсөв ',
      'Түр зогсоох',
      'Цуцлах',
      'Тодорхойлолт',
      'Дизайн · pen.dev',
      'Төлөвлөгөө',
      'Даалгавар',
      'Хөгжүүлэлт',
      ' · ажиллаж буй',
      'Нэгтгэх хүсэлт',
      'хүлээгдэж',
      'Гаралт',
      'Артефакт',
      'Ажиллуулах',
      'Мэдээлэл',
      'ШУУД',
      'Үр дүн',
      ' гаралт',
      'Шаардлага',
      'Арга барил',
      ' дэлгэц',
      'ui.pen + exports · pen.dev',
      ' commit',
      'хүлээгдэж · хүн шийднэ',
    ],
    omits: [
      {
        label: '4 даалгавар · Даалгавар агент',
        why: 'The run records the task list as a document, not how many tasks it holds; the row says what the document is for, as the other documents do.',
      },
    ],
  },
  {
    artboard: '07 Approval Checkpoint',
    files: [`${APP}/tickets/[id]/approve/+page.svelte`, `${UI}/TicketHead.svelte`, MN],
    takes: [
      'Даалгаврууд',
      'Таны батлалт хүлээж буй',
      ' үүсгэсэн',
      ' эхэлсэн',
      'одоогоор ',
      'Ажиллагаа цуцлах',
      'Хяналтын цэг: ',
      'код бичихээс өмнө',
      ' ажлаа дуусгалаа. Та батлах, өөрчлөлт хүсэх, эсвэл өөрөө засах хүртэл дамжлага түр зогсоно.',
      'Өөрчлөлт хүсэх',
      'Батлаад үргэлжлүүлэх',
      ' засах',
      'Таны тэмдэглэл ',
      ' засагдаад дахин энд зогсоно.',
      ' руу буцаах',
      'Явц',
      'дууссан',
      'Батлалт хүлээж буй',
      ' (та)',
    ],
    omits: [
      {
        label: 'Батлалт: Ana тодорхойлолтыг баталлаа',
        why: 'The timeline names a decision by what was decided; who decided it is recorded on the approval but the timeline has never carried it, and adding it is new behaviour, not presentation.',
      },
    ],
  },
  {
    artboard: '08 Pipeline Builder',
    files: [
      `${APP}/pipelines/[id]/+page.svelte`,
      `${UI}/PipelineBuilder.svelte`,
      `${UI}/StepNode.svelte`,
      'apps/web/src/lib/services/pipeline.ts',
    ],
    takes: [
      'Used by',
      'Drag steps into the order you want. Add a checkpoint anywhere a human should look before',
      'Duplicate',
      'Test run',
      'Open merge request',
      'Add a step',
      'Drag onto the canvas or click a + on a connector.',
      'Human checkpoint',
      'Pause until someone approves',
      'Design step',
      'Draw screens with the pen.dev CLI',
      'Agent step',
      'Run one of your agents via Claude CLI',
      'Shell command',
      'Run a script in the sandbox (lint, build)',
      'Notify',
      'Your agents',
      'Custom',
    ],
  },
  {
    artboard: '09 Agents',
    files: [`${APP}/agents/+page.svelte`, `${UI}/AgentCard.svelte`],
    takes: [
      'Each agent runs with its own instructions, model, tools and skills. The Design agent runs on the pen.dev CLI; the rest run on the Claude CLI.',
      'Default',
      'Conditional',
      'Custom',
      'Model',
      'Tools',
      'Skills',
      'Used in',
      'Edit',
    ],
  },
  {
    artboard: '10 Agent Editor',
    files: [`${APP}/agents/[id]/+page.svelte`],
    takes: [
      'Changes apply to new runs only. Running tickets keep the version they started with.',
      'Reset to default',
      'System prompt',
      'Model & limits',
      'Model',
      'Max cost per run',
      'Max time',
      'Max turns',
      'Allowed tools',
      'Passed to the CLI as --allowedTools',
      'Skills attached',
      'Manage skills',
      'Add',
    ],
    omits: [
      {
        label: 'Test in sandbox',
        why: 'Nothing behind it exists — a run needs an orchestrator and a container host — and a button that does nothing is worse than no button.',
      },
    ],
  },
  {
    artboard: '11 Skills',
    files: [`${APP}/skills/+page.svelte`],
    takes: [
      'Reusable instruction files any agent can use. They are copied into .claude/skills/ for each run.',
      'Search skills',
      'Used by',
      'History',
      'Delete',
      'Save skill',
      'Name',
      'Description (shown to the agent so it knows when to use this)',
      'Content (Markdown)',
      'Preview',
    ],
  },
  {
    artboard: '12 Settings',
    files: [`${APP}/settings/+page.svelte`],
    takes: [
      'Workspace',
      'Sandbox (Docker)',
      'Claude CLI & keys',
      'Design (pen.dev)',
      'Cost limits',
      'Members',
      'Notifications',
      'Test connection',
      'Sandbox · Docker',
      'Each run gets one fresh container with the repo, Claude CLI and your toolchain.',
      'Design · pen.dev',
      'Used only by design steps. Screens are exported as images and the .pen file is',
    ],
  },
  {
    artboard: '14 Design Review',
    files: [
      `${APP}/tickets/[id]/design/+page.svelte`,
      `${UI}/TicketHead.svelte`,
      `${UI}/ScreenGallery.svelte`,
      MN,
    ],
    takes: [
      'Даалгаврууд',
      'Дизайн батлахыг хүлээж буй',
      'Ажиллагаа цуцлах',
      'Хяналтын цэг: код бичихээс өмнө дэлгэцүүдийг хянана уу',
      'Дизайн агент pen.dev CLI-аар ',
      ' дэлгэц зурсан.',
      'Одоогоор юу ч хэрэгжүүлээгүй.',
      'Батлавал ',
      ' рүү шилжинэ.',
      'Өөрчлөлт хүсэх',
      'Батлаад үргэлжлүүлэх',
      'Дэлгэцүүд',
      ' экспортлосон',
      // The committed source, where it lives: opened, or fetched (FR-064e).
      'pen.dev дээр нээх',
      '.pen татах',
      'Яагаад энэ даалгаврыг зурсан бэ',
      'Тодорхойлолт агент шийдсэн · ',
      'Дэлгэцүүдийг эдгээртэй тулгана уу',
      'Батласны дараа',
    ],
    omits: [
      {
        label: 'Дизайн алхам · 2м 41с · $0.42',
        why: "The head carries what every ticket head carries — branch, author, start, spend — and the design step's own time and cost are under the column beside the screens, where the step is described.",
      },
    ],
  },
];
